base_url = "https://www.sujalbolia.com/"
title = "sujalbolia"
build_search_index = true
generate_feeds = true
compile_sass = true
minify_html = true

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "dark"
home_path = "/home/sujalbolia"
home_title = "home"

menu = [
    { name = "projects", url = "/projects", weight = 1 },
    { name = "posts", url = "/posts", weight = 2 },
    { name = "about.md", url = "/about", weight = 3 },
    { name = "resume.pdf", url = "/resume.pdf", weight = 4 },
]

socials = [
    { name = "github", url = "https://github.com/nextonesfaster/", icon = "github" },
    { name = "email", url = "mailto:sujalbolia@gmail.com", icon = "email" },
    { name = "linkedin", url = "https://www.linkedin.com/in/sujal-bolia/", icon = "linkedin" },
]

custom_css = []
